package com.insignia.subscription.dao;

import com.insignia.customExceptions.InvalidInputParametersException;
import com.insignia.subscription.model.SubscriptionRequest;
import com.insignia.subscription.model.SubscriptionResponse;

public interface SubscriptionDaoInterface {

	public SubscriptionResponse createSubscriptionPlan(SubscriptionRequest subscriptionRequest) throws InvalidInputParametersException;
	public SubscriptionResponse modifySubscriptionPlan(SubscriptionRequest subscriptionRequest) throws InvalidInputParametersException;
	public SubscriptionResponse deleteSubscriptionPlan(SubscriptionRequest subscriptionRequest) throws InvalidInputParametersException;
	public SubscriptionResponse activateSubscriptionPlan(SubscriptionRequest subscriptionRequest) throws InvalidInputParametersException;
	public SubscriptionResponse deactivateSubscriptionPlan(SubscriptionRequest subscriptionRequest) throws InvalidInputParametersException;
	public SubscriptionResponse findDetailsByPlanId(SubscriptionRequest subscriptionRequest) throws InvalidInputParametersException;
}
